# Hello. Welcome to cyberspace mysteries. This site is built with MKDocs (material theme) & Github pages.
site_name: cyberspacemysteries 
site_url: https://cyberspacemysteries.github.io
site_author: elidyweaver
site_description: exploring the why behind empowering technologies

# repository
repo_name: cyberspacemysteries/cyberspacemysteries.github.io
repo_url: https://github.com/cyberspacemysteries/cyberspacemysteries.github.io

# copyright
copyright: creative commons 0, except when sharing other projects or artworks. 

# theme design
theme: 
  name: material
  custom_dir: overrides
  language: en
  extra_css:
    - stylesheets/extra.css
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # toc.integrate

  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to day mode
    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to night mode
  font:
    text: Roboto
    code: Roboto Mono
    font: false
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  icon:
    repo: material/github
    tags:
      nostr: material/note/text
      bitcoin: material/bitcoin

# Plugins
plugins:
  - blog:
      enabled: true
      blog_dir: .
      blog_toc: true
      post_date_format: full
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 1
      post_excerpt: required
      post_excerpt_max_authors: 2
      post_excerpt_max_categories: 3
      post_excerpt_separator: <!-- excerpt ends before this -->
      post_readtime: true
      categories: true
      categories_name: Series
      categories_url_format: "series/{category}/{slug}"
      categories_toc: true
      authors: true
      authors_file: .authors.yml
      pagination: true
      pagination_per_page: 5
      pagination_url_format: "page/{page}"
      pagination_if_single_page: false
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      draft: false
      draft_on_serve: true
      draft_if_future_date: true
  - privacy
  - offline
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - tags

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      title: On this page
      permalink: ⚓︎
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 5
  - tables

# python markdown extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: cyberspacemysteries
      repo: cyberspacemysteries.github.io
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# page tree
nav:
  - About: 
    - 'About': index.md
  - Series: 
    - 'BUIDL HODL': 
      - 'principles': buidl-hodl/index.md
      - 'Nostr in time': buidl-hodl/time/before-and-after/nostr/index.md
