authors:
  cyberspacemysteries:
    name: cyberspace mysteries 
    description: exploring empowering tech
    avatar: https://avatars.githubusercontent.com/u/121465261
    url: https://github.io/cyberspacemysteries
  elidyweaver:
    name: elidy weaver 
    description: exploring empowering tech
    avatar: https://avatars.githubusercontent.com/u/119618812
    url: https://github.io/elidyweaver