authors:
  cyberspacemysteries:
    name: cyberspace mysteries 
    description: An in-depth look at the principles behind technology
    avatar: https://avatars.githubusercontent.com/u/121465261
    url: https://github.com/cyberspacemysteries
  elidyweaver:
    name: elidy weaver 
    description: exploring ways of healing our connection to technology
    avatar: https://avatars.githubusercontent.com/u/119618812
    url: https://github.com/elidyweaver